# -*- coding: utf-8 -*-
"""Arabic terms for the Sales Representative Portal (rendered at runtime by i18n.T)."""

AR = {
    # --- navigation / generic
    "Home": "الرئيسية",
    "Route": "خط السير",
    "Customers": "العملاء",
    "Orders": "الطلبات",
    "More": "المزيد",
    "Main": "الرئيسي",
    "Log out": "تسجيل الخروج",
    "Notifications": "الإشعارات",
    "Visit in progress:": "زيارة جارية:",
    "All": "الكل",
    "Filter": "تصفية",
    "Open": "فتح",
    "Unpaid": "غير مسددة",
    "Upload": "رفع",
    "Call": "اتصال",
    "WhatsApp": "واتساب",
    "Open location": "فتح الموقع",
    "Back to home": "الرجوع للرئيسية",
    "No access": "غير مسموح",
    "This page is not available for your account. If you should have access, ask your manager to link your user to a sales representative.":
        "هذه الصفحة غير متاحة لحسابك. لو المفروض يكون لك صلاحية، اطلب من مديرك ربط مستخدمك بمندوب مبيعات.",
    # --- dashboard
    "Sales today": "مبيعات اليوم",
    "Visits today": "زيارات اليوم",
    "Done / remaining": "المنفذ / المتبقي",
    "Orders today": "طلبات اليوم",
    "Invoices / payments": "الفواتير / الدفعات",
    "New visit": "زيارة جديدة",
    "New order": "طلب جديد",
    "New invoice": "فاتورة جديدة",
    "My route": "خط سيري",
    "My customers": "عملائي",
    "My stock": "مخزني",
    "My orders": "طلباتي",
    "My invoices": "فواتيري",
    "My payments": "دفعاتي",
    "My collections": "تحصيلاتي",
    "My operations": "عملياتي",
    "Payment": "دفعة",
    "Payments": "الدفعات",
    "Invoice": "فاتورة",
    "Invoices": "الفواتير",
    "Visits": "الزيارات",
    "Stock operation": "عملية مخزون",
    "Transfers & deliveries": "التحويلات والتسليمات",
    "Deliveries": "التسليمات",
    "Returns": "المرتجعات",
    # --- customers
    "Search customers": "ابحث في العملاء",
    "Search products": "ابحث في المنتجات",
    "No customers found. Ask your manager to assign customers to you.": "لا يوجد عملاء. اطلب من مديرك تخصيص عملاء لك.",
    "Salesperson:": "المندوب:",
    "Last visit:": "آخر زيارة:",
    "Last order:": "آخر طلب:",
    "Last payment:": "آخر دفعة:",
    "Due": "مستحق",
    "due": "مستحق",
    "Standing at the customer's door? Save this spot as the customer location.": "واقف عند باب العميل؟ احفظ هذا المكان كموقع للعميل.",
    "Save current location": "حفظ الموقع الحالي",
    "Sales orders": "أوامر البيع",
    # --- route / visits
    "All routes": "كل خطوط السير",
    "All areas": "كل المناطق",
    "Any priority": "أي أولوية",
    "Normal": "عادية",
    "High": "عالية",
    "Urgent": "عاجلة",
    "No visits for this day. Add a one-off visit or ask your manager for a route.": "لا توجد زيارات لهذا اليوم. أضف زيارة منفردة أو اطلب خط سير من مديرك.",
    "+ New visit": "+ زيارة جديدة",
    "Start visit": "بدء الزيارة",
    "End visit": "إنهاء الزيارة",
    "Cancel visit": "إلغاء الزيارة",
    "No visits yet.": "لا توجد زيارات بعد.",
    "Choose a customer": "اختر عميلًا",
    "Customer": "العميل",
    "Visit type": "نوع الزيارة",
    "Sales visit": "زيارة مبيعات",
    "Collection visit": "زيارة تحصيل",
    "Delivery visit": "زيارة تسليم",
    "Follow up": "متابعة",
    "Complaint": "شكوى",
    "Other": "أخرى",
    "Your location is recorded once, when you start the visit.": "يتم تسجيل موقعك مرة واحدة فقط عند بدء الزيارة.",
    "Started:": "البدء:",
    "Ended:": "الانتهاء:",
    "Result:": "النتيجة:",
    "Next visit:": "الزيارة القادمة:",
    "Visit result": "نتيجة الزيارة",
    "Order taken": "تم أخذ طلب",
    "Payment collected": "تم تحصيل دفعة",
    "No order": "بدون طلب",
    "Customer closed": "العميل مغلق",
    "Follow-up needed": "تحتاج متابعة",
    "Notes": "ملاحظات",
    "Note": "ملاحظة",
    "Next visit date": "تاريخ الزيارة القادمة",
    "Photos or documents": "صور أو مستندات",
    "From this visit": "من هذه الزيارة",
    "Attachments": "المرفقات",
    "Attachment": "مرفق",
    "No files yet.": "لا توجد ملفات بعد.",
    "Create order": "إنشاء الطلب",
    "Create invoice": "إنشاء فاتورة",
    "Register payment": "تسجيل دفعة",
    "Draft invoice": "فاتورة مسودة",
    # --- orders
    "Quotation": "عرض سعر",
    "Sent": "مرسل",
    "Confirmed": "مؤكد",
    "Delivered": "تم التسليم",
    "Invoiced": "تم إصدار فاتورة",
    "Cancelled": "ملغي",
    "Locked": "مقفل",
    "Quotation Sent": "عرض سعر مرسل",
    "+ New order": "+ طلب جديد",
    "No orders here yet.": "لا توجد طلبات هنا بعد.",
    "Created from the Sales Representative Portal": "تم الإنشاء من بوابة مندوب المبيعات",
    "Product": "المنتج",
    "Products": "المنتجات",
    "Qty": "الكمية",
    "Quantity": "الكمية",
    "Price": "السعر",
    "Disc.": "خصم",
    "Discount %": "الخصم %",
    "Subtotal": "الإجمالي الفرعي",
    "Taxes": "الضرائب",
    "Total": "الإجمالي",
    "Total:": "الإجمالي:",
    "UoM": "الوحدة",
    "Edit order": "تعديل الطلب",
    "Confirm order": "تأكيد الطلب",
    "Cancel order": "إلغاء الطلب",
    "Save changes": "حفظ التعديلات",
    "Save and confirm": "حفظ وتأكيد",
    "Save quotation": "حفظ عرض السعر",
    "+ Add product": "+ إضافة منتج",
    "Search by name or code": "ابحث بالاسم أو الكود",
    "Remove line": "حذف السطر",
    "Maximum discount is {cap}%": "الحد الأقصى للخصم {cap}%",
    # --- invoices / payments
    "No invoices here yet.": "لا توجد فواتير هنا بعد.",
    "Draft": "مسودة",
    "Paid": "مسددة",
    "Date": "التاريخ",
    "Residual": "المتبقي",
    "Download PDF": "تحميل PDF",
    "+ Register payment": "+ تسجيل دفعة",
    "No payments yet.": "لا توجد دفعات بعد.",
    "No payment method is assigned to you.": "لا توجد طريقة دفع مخصصة لك.",
    "Ask your manager to allow at least one payment method on your profile.": "اطلب من مديرك السماح بطريقة دفع واحدة على الأقل في ملفك.",
    "Payment amount": "مبلغ الدفعة",
    "Payment method": "طريقة الدفع",
    "Payment date": "تاريخ الدفعة",
    "Reference": "المرجع",
    "Amount": "المبلغ",
    "Today's collection": "تحصيل اليوم",
    "This week": "هذا الأسبوع",
    "This month": "هذا الشهر",
    "Cash": "نقدي",
    "Bank": "بنك",
    "Cheques": "الشيكات",
    "Recent collections": "آخر التحصيلات",
    "Nothing collected yet.": "لم يتم تحصيل شيء بعد.",
    # --- stock
    "Stock view is disabled.": "عرض المخزون غير مفعّل.",
    "No warehouse is assigned to you yet.": "لم يتم تخصيص مخزن لك بعد.",
    "No stock in": "لا يوجد مخزون في",
    "Receive stock": "استلام مخزون",
    "Return stock": "إرجاع مخزون",
    "Transfer": "تحويل",
    "Available": "المتاح",
    "Reserved": "المحجوز",
    "Demand": "المطلوب",
    "Done": "تم",
    "Destination warehouse": "المخزن الوجهة",
    "Create operation": "إنشاء العملية",
    "Nothing here yet.": "لا يوجد شيء هنا بعد.",
    "Validate delivery": "تأكيد التسليم",
    # --- notifications
    "You're all caught up.": "لا توجد إشعارات جديدة.",
    "Order confirmed": "تم تأكيد الطلب",
    "Order cancelled": "تم إلغاء الطلب",
    "Invoice issued": "تم إصدار فاتورة",
    "Payment registered": "تم تسجيل دفعة",
    "New visit ": "",
    "New route": "خط سير جديد",
    "Route changed": "تم تغيير خط السير",
    # --- selection labels shown in the portal
    "Planned": "مخططة",
    "Started": "بدأت",
    "Completed": "مكتملة",
    "Missed": "فائتة",
    "Sales Visit": "زيارة مبيعات",
    "Collection Visit": "زيارة تحصيل",
    "Delivery Visit": "زيارة تسليم",
    "Follow Up": "متابعة",
    "Order Taken": "تم أخذ طلب",
    "Payment Collected": "تم تحصيل دفعة",
    "No Order": "بدون طلب",
    "Customer Closed": "العميل مغلق",
    "Follow-up Needed": "تحتاج متابعة",
    "Waiting Another Operation": "في انتظار عملية أخرى",
    "Waiting": "في الانتظار",
    "Ready": "جاهز",
    "In Process": "قيد المعالجة",
    "Rejected": "مرفوضة",
    "Posted": "مرحّلة",
    # --- messages & titles (python)
    "%s file(s) uploaded.": "تم رفع %s ملف.",
    "Add at least one product.": "أضف منتجًا واحدًا على الأقل.",
    "Choose a destination warehouse.": "اختر المخزن الوجهة.",
    "Choose an open invoice.": "اختر فاتورة مفتوحة.",
    "Choose one of your allowed payment methods.": "اختر إحدى طرق الدفع المسموح لك بها.",
    "Choose one of your customers.": "اختر أحد عملائك.",
    "Creating orders is disabled.": "إنشاء الطلبات غير مفعّل.",
    "Customer location saved.": "تم حفظ موقع العميل.",
    "Delivery validated.": "تم تأكيد التسليم.",
    "Direct invoicing is disabled.": "الفوترة المباشرة غير مفعّلة.",
    "Direct invoicing is disabled. Create invoices from a confirmed order.": "الفوترة المباشرة غير مفعّلة. أنشئ الفواتير من طلب مؤكد.",
    "Discount for %(p)s cannot exceed %(c)s%%.": "الخصم على %(p)s لا يمكن أن يزيد عن %(c)s%%.",
    "Edit %s": "تعديل %s",
    "End the current visit before starting a new one.": "أنهِ الزيارة الحالية قبل بدء زيارة جديدة.",
    "Internal Transfer": "تحويل داخلي",
    "Invoice created.": "تم إنشاء الفاتورة.",
    "Invoice creation is not allowed.": "إنشاء الفواتير غير مسموح.",
    "Location not available. Enable GPS and try again.": "الموقع غير متاح. فعّل الـ GPS وحاول مرة أخرى.",
    "My Collections": "تحصيلاتي",
    "My Invoices": "فواتيري",
    "My Orders": "طلباتي",
    "My Payments": "دفعاتي",
    "My Route": "خط سيري",
    "My Stock": "مخزني",
    "New Invoice": "فاتورة جديدة",
    "New Sales Order": "أمر بيع جديد",
    "New Visit": "زيارة جديدة",
    "No file uploaded.": "لم يتم رفع ملف.",
    "No warehouse is assigned to you. Contact your manager.": "لا يوجد مخزن مخصص لك. تواصل مع مديرك.",
    "Not allowed.": "غير مسموح.",
    "Nothing to invoice on this order.": "لا يوجد ما يُفوتر في هذا الطلب.",
    "Operation %s created.": "تم إنشاء العملية %s.",
    "Order %s created.": "تم إنشاء الطلب %s.",
    "Order cancelled.": "تم إلغاء الطلب.",
    "Order confirmed.": "تم تأكيد الطلب.",
    "Order updated.": "تم تحديث الطلب.",
    "Payment amount must be greater than zero.": "مبلغ الدفعة يجب أن يكون أكبر من صفر.",
    "Payment cannot exceed the remaining amount (%s).": "الدفعة لا يمكن أن تزيد عن المبلغ المتبقي (%s).",
    "Payment registered.": "تم تسجيل الدفعة.",
    "Payment registration is disabled.": "تسجيل الدفعات غير مفعّل.",
    "Product not found.": "المنتج غير موجود.",
    "Quantity must be greater than zero for %s.": "الكمية يجب أن تكون أكبر من صفر للمنتج %s.",
    "Receive Stock": "استلام مخزون",
    "Register Payment": "تسجيل دفعة",
    "Return Stock": "إرجاع مخزون",
    "Stock Operation": "عملية مخزون",
    "Stock operations are disabled.": "عمليات المخزون غير مفعّلة.",
    "The main warehouse is not configured in the portal settings.": "لم يتم ضبط المخزن الرئيسي في إعدادات البوابة.",
    "This action is not allowed.": "هذا الإجراء غير مسموح.",
    "This delivery needs manual processing in the back office.": "هذا التسليم يحتاج معالجة يدوية من المكتب.",
    "This operation is not allowed.": "هذه العملية غير مسموحة.",
    "This order can no longer be cancelled from the portal.": "لا يمكن إلغاء هذا الطلب من البوابة بعد الآن.",
    "This order can no longer be edited from the portal.": "لا يمكن تعديل هذا الطلب من البوابة بعد الآن.",
    "This order cannot be confirmed.": "لا يمكن تأكيد هذا الطلب.",
    "Transfers & Deliveries": "التحويلات والتسليمات",
    "Visit cancelled.": "تم إلغاء الزيارة.",
    "Visit completed.": "تم إنهاء الزيارة.",
    "Visit started.": "تم بدء الزيارة.",
    "You cannot validate this transfer.": "لا يمكنك تأكيد هذا التحويل.",
    # --- model-level user errors surfaced in the portal
    "Only a planned visit can be started.": "يمكن بدء الزيارة المخططة فقط.",
    "Only a started visit can be ended.": "يمكن إنهاء الزيارة التي بدأت فقط.",
    "A completed visit cannot be cancelled.": "لا يمكن إلغاء زيارة مكتملة.",
}
AR.pop("New visit ", None)
AR["New visit"] = "زيارة جديدة"

AR.update({
    "Save the location of at least two customers first.": "احفظ موقع عميلين على الأقل أولًا.",
    "Visits re-ordered by distance.": "تم ترتيب الزيارات حسب الأقرب.",
    "Re-order the remaining visits so the nearest customer comes first, starting from where you are now.":
        "رتّب الزيارات المتبقية بحيث يأتي أقرب عميل أولًا، بدءًا من مكانك الحالي.",
    "Optimize from my location": "ترتيب الأقرب أولًا من موقعي",
    "You are offline. Saved pages are available; saving is disabled until you reconnect.":
        "أنت غير متصل بالإنترنت. الصفحات المحفوظة متاحة، والحفظ متوقف حتى يعود الاتصال.",
    "At least two customers with a saved location are needed to optimize \"%s\".":
        "لازم عميلين على الأقل بموقع محفوظ لترتيب \"%s\".",
    "Route \"%s\" was re-ordered by distance.": "تم ترتيب خط السير \"%s\" حسب المسافة.",
})

AR.update({
    "Choose from list": "اختر من القائمة",
    "Validate automatically": "تأكيد تلقائي",
    "Operation %s created and validated.": "تم إنشاء العملية %s وتأكيدها.",
    "Operation %(n)s created but not validated: %(r)s": "تم إنشاء العملية %(n)s لكن لم يتم تأكيدها: %(r)s",
    "not enough stock to cover all lines": "المخزون لا يكفي لكل البنود",
    "it needs manual processing in the back office": "تحتاج معالجة يدوية من المكتب",
    "validation did not complete": "لم يكتمل التأكيد",
    "The payment could not be created. Please check the journal configuration.": "تعذر إنشاء الدفعة. راجع إعدادات دفتر اليومية.",
})

AR.update({
    "Delivery validated": "تم تأكيد التسليم",
    "Delivery not validated": "لم يتم تأكيد التسليم",
    "This transfer needs manual processing.": "هذا التحويل يحتاج معالجة يدوية.",
    "%s is waiting: not enough stock or it needs manual processing.": "%s في الانتظار: المخزون لا يكفي أو يحتاج معالجة يدوية.",
    "Order %s created and delivery validated.": "تم إنشاء الطلب %s وتأكيد التسليم.",
    "Order %s created; the delivery was not validated (not enough stock or manual processing needed).":
        "تم إنشاء الطلب %s لكن لم يتم تأكيد التسليم (المخزون لا يكفي أو يحتاج معالجة يدوية).",
    "Order confirmed and delivery validated.": "تم تأكيد الطلب وتأكيد التسليم.",
    "Order confirmed; the delivery was not validated (not enough stock or manual processing needed).":
        "تم تأكيد الطلب لكن لم يتم تأكيد التسليم (المخزون لا يكفي أو يحتاج معالجة يدوية).",
})

AR.update({
    "Choose or search a product": "اختر أو ابحث عن منتج",
    "No products found": "لا توجد منتجات",
    "Loading…": "جاري التحميل…",
    "Showing the first results, type to narrow the list": "تظهر أول النتائج، اكتب لتضييق القائمة",
})

AR.update({
    "+ New Customer": "+ عميل جديد", "+ New Expense": "+ مصروف جديد", "+ New Follow-up": "+ متابعة جديدة",
    "1-30 Days": "1-30 يوم", "31-60 Days": "31-60 يوم", "61-90 Days": "61-90 يوم", "90+ Days": "أكثر من 90 يوم",
    "Achieved": "المحقق", "Add Follow-up": "إضافة متابعة", "Add Note": "إضافة ملاحظة", "Add a note": "أضف ملاحظة",
    "Address": "العنوان", "Approved": "معتمد", "Back to the visit": "الرجوع للزيارة", "Balance:": "الرصيد:",
    "Cancel": "إلغاء", "Cheque Date": "تاريخ الشيك", "Cheque Details": "بيانات الشيك", "Cheque Number": "رقم الشيك",
    "Cheque photo": "صورة الشيك", "Choose the expense type.": "اختر نوع المصروف.",
    "Choose the invoice or sales order": "اختر الفاتورة أو أمر البيع",
    "Choose the invoice or sales order to return from.": "اختر الفاتورة أو أمر البيع المراد الإرجاع منه.",
    "Choose the reason": "اختر السبب",
    "Choose the result": "اختر النتيجة",
    "Choose the return reason for every product.": "اختر سبب الإرجاع لكل منتج.",
    "Choose the visit result before finishing.": "اختر نتيجة الزيارة قبل إنهائها.",
    "City": "المدينة", "Cleared": "تم التحصيل", "Close": "إغلاق", "Code:": "الكود:", "Collect": "تحصيل",
    "Collect Payment": "تحصيل دفعة", "Collect payment": "تحصيل دفعة", "Company": "شركة",
    "Completed / Pending": "المكتملة / المعلقة", "Create Return": "إنشاء المرتجع", "Current": "غير مستحق",
    "Customer Name": "اسم العميل", "Customer Return": "مرتجع عميل", "Customer Search": "بحث العملاء",
    "Customer Type": "نوع العميل", "Customer saved.": "تم حفظ العميل.",
    "Customer saved. It is waiting for approval.": "تم حفظ العميل وهو في انتظار الاعتماد.",
    "Customers owing money": "العملاء المدينون", "Customers to Visit Today": "عملاء يجب زيارتهم اليوم",
    "Default": "الافتراضي", "Delete": "حذف", "Deliveries & Returns": "التسليمات والمرتجعات", "Deposited": "تم الإيداع",
    "Describe the task.": "اكتب وصف المهمة.", "Details": "التفاصيل", "Due Date": "تاريخ الاستحقاق",
    "Due Date:": "تاريخ الاستحقاق:", "Enter a mobile or phone number.": "أدخل رقم موبايل أو تليفون.",
    "Enter the customer name.": "أدخل اسم العميل.", "Enter the quantity to return.": "أدخل الكمية المراد إرجاعها.",
    "Expense Type": "نوع المصروف", "Expense deleted.": "تم حذف المصروف.", "Expense saved.": "تم حفظ المصروف.",
    "Expense submitted for approval.": "تم إرسال المصروف للاعتماد.", "Expenses": "المصروفات",
    "Finish Visit": "إنهاء الزيارة", "Follow-up": "متابعة", "Follow-up saved.": "تم حفظ المتابعة.",
    "Follow-up updated.": "تم تحديث المتابعة.", "Follow-ups": "المتابعات",
    "For a cheque, enter the cheque number, the bank and the due date.": "للشيك أدخل رقم الشيك والبنك وتاريخ الاستحقاق.",
    "High-value customer": "عميل ذو قيمة عالية", "Individual": "فرد", "Invoice / Sales Order": "فاتورة / أمر بيع",
    "Invoice(s)": "الفاتورة/الفواتير", "Last Order": "آخر طلب", "Last Visit": "آخر زيارة", "Last price": "آخر سعر",
    "Mark Done": "تم التنفيذ", "Max": "الحد الأقصى", "Missed the last visit": "فاتته الزيارة الأخيرة", "Mobile": "موبايل",
    "Monthly Collection": "تحصيل الشهر", "Monthly Sales": "مبيعات الشهر", "My Cheques": "شيكاتي", "My Targets": "أهدافي",
    "Never visited": "لم تتم زيارته أبدًا", "New Customer": "عميل جديد", "New Customers (month)": "عملاء جدد (الشهر)",
    "New Expense": "مصروف جديد", "New Follow-up": "متابعة جديدة", "New Order": "طلب جديد", "New Quotation": "عرض سعر جديد",
    "New customers wait for your manager's approval before you can sell to them.": "العملاء الجدد ينتظرون اعتماد المدير قبل أن تتمكن من البيع لهم.",
    "Next Follow-up Date": "تاريخ المتابعة القادمة", "Next Visit Date": "تاريخ الزيارة القادمة",
    "Next customer:": "العميل التالي:", "No cheques here yet.": "لا توجد شيكات هنا بعد.", "No customer": "بدون عميل",
    "No expenses here yet.": "لا توجد مصروفات هنا بعد.", "No open follow-ups.": "لا توجد متابعات مفتوحة.",
    "No order for %s days": "لا يوجد طلب منذ %s يوم", "No order yet": "لا يوجد طلب حتى الآن", "No recent order": "بدون طلب حديث",
    "No return operation type is configured for this warehouse.": "لم يتم ضبط نوع عملية المرتجع لهذا المخزن.",
    "No target is set for this period. Ask your manager.": "لا يوجد هدف لهذه الفترة. اسأل مديرك.",
    "No visit": "بدون زيارة", "Not visited": "لم تتم زيارتهم", "Not visited for %s days": "لم تتم زيارته منذ %s يوم",
    "Note added.": "تمت إضافة الملاحظة.", "Nothing can be returned for this customer": "لا يوجد ما يمكن إرجاعه لهذا العميل",
    "Nothing is outstanding.": "لا توجد مبالغ مستحقة.", "Offline": "غير متصل", "On today's route": "على مسار اليوم",
    "Online": "متصل", "Only a draft expense can be deleted.": "يمكن حذف المصروف المسودة فقط.", "Open Customer": "فتح العميل",
    "Outstanding": "المستحق", "Outstanding %s": "مستحق %s", "Outstanding & Aging": "المستحقات وأعمار الديون",
    "Outstanding invoices": "الفواتير المستحقة", "Overdue": "متأخر", "Overdue %s": "متأخر %s",
    "Overdue Follow-ups": "متابعات متأخرة", "Overdue:": "المتأخرة:", "Payment Date": "تاريخ الدفعة",
    "Payment Method": "طريقة الدفع", "Payment Receipt": "إيصال دفع", "Payment Terms": "شروط الدفع",
    "Payment Terms:": "شروط الدفع:", "Phone": "تليفون", "Previous periods": "الفترات السابقة", "Price List": "قائمة الأسعار",
    "Print Receipt": "طباعة الإيصال", "Priority": "الأولوية", "Products bought before": "منتجات اشتراها من قبل",
    "Purpose:": "الغرض:", "Quick Actions": "إجراءات سريعة", "Quotations": "عروض الأسعار", "Ranking": "الترتيب",
    "Receipt photo": "صورة الإيصال", "Received": "تم الاستلام", "Refusal Reason:": "سبب الرفض:", "Refused": "مرفوض",
    "Remaining": "المتبقي", "Reorder expected (every ~%s days)": "إعادة الطلب متوقعة (كل ~%s يوم)", "Return": "مرتجع",
    "Return %s created.": "تم إنشاء المرتجع %s.", "Return Reason": "سبب الإرجاع", "Return of %s": "مرتجع من %s",
    "Return quantity for %(p)s cannot exceed %(m)s.": "كمية المرتجع للمنتج %(p)s لا يمكن أن تزيد عن %(m)s.",
    "Returned": "مرتجع", "Sales Representative": "مندوب المبيعات", "Save Customer": "حفظ العميل", "Save Draft": "حفظ كمسودة",
    "Save Follow-up": "حفظ المتابعة", "Search name, mobile, code or address": "ابحث بالاسم أو الموبايل أو الكود أو العنوان",
    "Start Visit": "بدء الزيارة", "Submit": "إرسال", "Submitted": "تم الإرسال", "Syncing": "جاري المزامنة", "Target": "الهدف",
    "Target Achievement": "تحقيق الهدف", "Task": "المهمة", "The expense amount must be greater than zero.": "مبلغ المصروف يجب أن يكون أكبر من صفر.",
    "This customer is waiting for approval.": "هذا العميل في انتظار الاعتماد.",
    "This expense cannot be submitted.": "لا يمكن إرسال هذا المصروف.", "This product cannot be returned.": "لا يمكن إرجاع هذا المنتج.",
    "Today's Collections": "تحصيلات اليوم", "Today's Follow-ups": "متابعات اليوم", "Today's Orders": "طلبات اليوم",
    "Today's Sales": "مبيعات اليوم", "Today's Visits": "زيارات اليوم", "Today:": "اليوم:", "Total Collected": "إجمالي المحصّل",
    "Total Outstanding": "إجمالي المستحق", "Total Overdue": "إجمالي المتأخر", "Total Sales": "إجمالي المبيعات",
    "Upcoming Follow-ups": "متابعات قادمة", "Upcoming:": "القادمة:", "Visit": "زيارة", "Visit Notes": "ملاحظات الزيارة",
    "Visit Result": "نتيجة الزيارة", "Visited today": "تمت زيارتهم اليوم", "With outstanding": "عليهم مستحقات",
    "Your GPS location is saved with the customer when you save.": "يتم حفظ موقعك (GPS) مع العميل عند الحفظ.",
    "created the %s from the portal": "أنشأ %s من البوابة", "created the customer from the portal": "أنشأ العميل من البوابة",
    "created the expense": "أنشأ المصروف", "created the return of %(l)s from %(p)s": "أنشأ مرتجع %(l)s من %(p)s",
    "d": "ي", "open invoices": "فواتير مفتوحة", "order": "الطلب", "overdue": "متأخر", "quotation": "عرض السعر",
    "registered %(a)s for invoice %(i)s": "سجّل %(a)s للفاتورة %(i)s",
    "registered a payment of %s from the portal": "سجّل دفعة %s من البوابة", "waiting to sync": "في انتظار المزامنة",
    # selection labels used by the portal
    "Order Created": "تم إنشاء طلب", "Customer Not Available": "العميل غير متاح", "Follow-up Required": "تحتاج متابعة",
    "New Customer Opportunity": "فرصة عميل جديد", "Complaint": "شكوى", "Waiting Approval": "في انتظار الاعتماد",
    "Transportation": "مواصلات", "Fuel": "وقود", "Parking": "انتظار سيارات", "Customer Visit Expenses": "مصروفات زيارة عميل",
    "Meals": "وجبات", "Customer visit": "زيارة عميل", "Sales": "المبيعات", "Collection": "التحصيل", "Orders": "الطلبات",
    "Visits": "الزيارات", "New Customers": "عملاء جدد",
})

AR.update({
    "This action needs an internet connection.": "هذا الإجراء يحتاج اتصالًا بالإنترنت.",
    "Saved on this device. It will sync when you are back online.": "تم الحفظ على الجهاز وستتم المزامنة عند عودة الاتصال.",
    "Photos were not saved offline; add them later.": "الصور لا تُحفظ بدون إنترنت؛ أضفها لاحقًا.",
    "could not be saved": "تعذر حفظه",
    "You are offline. Saved pages stay available; visits, notes, follow-ups, expenses, new customers and quotations are saved on the device and synced later.":
        "أنت غير متصل. الصفحات المحفوظة متاحة، والزيارات والملاحظات والمتابعات والمصروفات والعملاء الجدد وعروض الأسعار تُحفظ على الجهاز وتتم مزامنتها لاحقًا.",
    "Stock": "المخزون",
})
